/*
 * *****************************************************************************
 *               MCTI - Ministério da Ciência, Tecnologia e Inovação             
 *                INPE - Instituto Nacional de Pesquisas Espaciais               
 * -----------------------------------------------------------------------------
 * André Aparecido de S. Ivo <andre.ivo@inpe.br>        
 * *****************************************************************************
 */
package sysvap.gui;

import java.awt.Color;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import sysvap.gui.helper.SysActionsGUI;
import sysvap.gui.helper.vartwatch.SysVarWatchTableModel;

/**
 *
 * @author Ivo
 */
public final class JTableVarWatch extends JTable {

    private SysView form;

    /**
     * Creates new form JPanelPropertyEditor
     */
    public JTableVarWatch() {
        initComponents();

        //  Create the table with default data
        this.setShowGrid(false);
        this.setShowVerticalLines(true);
        this.setShowHorizontalLines(true);
        this.setDefaultRenderer(Object.class, getRender());
        this.getTableHeader().setReorderingAllowed(false);

        setObjScriptDebugging();
    }

    public SysView getForm() {
        return form;
    }

    public void setForm(SysView form) {
        this.form = form;
    }


    public void setObjScriptDebugging() {
        Object[][] dataProperties = null;
        String[] columnNames = {"Variable", "Value"};

        SysVarWatchTableModel model = new SysVarWatchTableModel(dataProperties, columnNames);
        this.setModel(model);
    }

    public DefaultTableCellRenderer getRender() {
        return new DefaultTableCellRenderer() {
            private Color whiteColor = new Color(255, 255, 255);
            private Color alternateColor = new Color(215, 240, 255);
            private Color selectedColor = new Color(51, 153, 255);

            @Override
            public Component getTableCellRendererComponent(JTable table,
                    Object value, boolean selected, boolean focused, int row,
                    int column) {

                super.getTableCellRendererComponent(table, value, selected,
                        focused, row, column);

                Color bg;
                if (!selected) {
                    bg = (column == 1 ? alternateColor : whiteColor);
                } else {
                    bg = selectedColor;
                }

                setBackground(bg);
                setForeground(selected ? Color.white : Color.black);

                if (value instanceof ImageIcon) {
                    setIcon((ImageIcon) value);
                    setText("");
                } else {
                    setIcon(null);
                }
                return this;
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        SysActionsGUI.KeyReleased(evt, getForm());
    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public TableCellEditor getCellEditor(int row, int column) {
        try {
            switch (column) {
                case 0:
                    return getDefaultEditor(String.class);
                case 1:
                    return getDefaultEditor(String.class);
            }


        } catch (Exception ex) {
            System.out.println("Error getCellEditor: " + ex.getMessage());
        }
        return getDefaultEditor(String.class);
    }

    @Override
    public TableCellRenderer getCellRenderer(int row, int column) {
        try {
            switch (column) {
                case 0:
                    return getDefaultRenderer(String.class);
                case 1:
                    return getDefaultRenderer(String.class);
            }
        } catch (Exception ex) {
            System.out.println("Error getCellRenderer: " + ex.getMessage());
        }
        return getDefaultRenderer(String.class);
    }
}
